### ISSUE TITLE
Nextcloud 18 support?

### ISSUE THREAD

**Issue by Michi-4G** [DJaeger/files_external_dropbox#11]
Thanks a lot for this great great plugin!

I noticed even the latest release explicitly mentions support for version 15 - 17 only?
What about official support for version 18 of Nextcloud?

I have tried to plugin installed on my Nextcloud v18.0.3 instance without any issues and it seems to work like charm (from a user perspective).
So I wonder, why it is still not officially supported?

Let me know if there is anything I could help with.

**Comment by DJaeger** [comment]
Because I have not tested with v18 until now and only have one response from @tmerten, that its working.

I will test next days and release for v18.
Thanks for your test.

**Comment by tmerten** [comment]
Hi @DJaeger : Login worked fine but afterwards I got a stack trace. I am unsure whether this is some mis-configuration of mine or an actual bug but I will test the update version and report it here.

Here is the link to the comment with the stack trace attached: https://github.com/DJaeger/files_external_dropbox/issues/6#issuecomment-608514193

**Comment by DJaeger** [comment]
Your stack trace tells that creating storage failed, wich is not the case as you said.
But there seems to be some testing funktion triggered.
Maybe the test implementation is not working

**Comment by tmerten** [comment]
I'm not really fluent in PHP but in some other languages. I guess I can still help logging/testing some simple things if you need more info.

**Comment by DJaeger** [comment]
You could try to do a clean reinstall with the most current version on v18 with debugging log level activated before and see if the error occures again.
Thanks in advance

**Comment by DJaeger** [comment]
I have now tested and used for some days
As it seems you also had no more errors I have now published v1.4.0 with support for nc18
