### ISSUE TITLE
No installation script ?

### ISSUE THREAD

**Issue by Darkaird** [DJaeger/files_external_dropbox#12]
Even with your well explained installation process, I like to have some installation script as it makes the process easier.
I made one, you might want to add it as an example (or not), here it is :
```sh
#!/usr/bin/env sh
version="1.3.0"

# Install requirements
apt -y update && \
apt -y install wget unzip git && \

# Download and extract archive
wget https://github.com/DJaeger/files_external_dropbox/archive/v$version.zip -O files_external_dropbox.zip && \
rm -rf files_external_dropbox && \
unzip -o files_external_dropbox.zip -d files_external_dropbox && \
rm files_external_dropbox.zip && \
chown -R www-data:root files_external_dropbox && \

# Create and enable plugin
su -l www-data -s /bin/bash -c "make --directory html/files_external_dropbox/files_external_dropbox-$version" && \
su -l www-data -s /bin/bash -c "html/occ app:enable files_external" && \
su -l www-data -s /bin/bash -c "html/occ app:enable files_external_dropbox"
``` 
And by the way, you may want to update the `README.md` to edit the source link to the `1.3.0`.

**Comment by DJaeger** [comment]
No, theres no installation script, as I don't think ist usefull, as you only need to install the app once.
I clearified the installation proces some more in the README.
If you choose to use the source way of installation, you should know what to do, as its not for the usual user and in most cases not in common environments.

If you want you could paste it as Gist and I mention it, but than please take care to update it, if theres a new version.

And by the way, your script uses different/wrong directories
