### ISSUE TITLE
Missing oc_external_mounts table

### ISSUE THREAD

**Issue by cflep** [DJaeger/files_external_dropbox#14]
After install the app, I couldn't log in.

To fix it, disable files_external.

for snap-installed Nextcloud:
cd /snap/bin
sudo su
./nextcloud.occ app:disable files_external

**Comment by ismailyenigul** [comment]
You need to enable first files_external plugin then file_external_dropbox

#15 my comment for the details

**Comment by DJaeger** [comment]
Fixed by 469ab4d28cc648bc210d081f8032ae26d3f0da05
