### ISSUE TITLE
problems creating Dropbox API

### ISSUE THREAD

**Issue by guidovanharten** [DJaeger/files_external_dropbox#16]
When creating the API I only see one line to adding global storages. Do I have a look in another section?

**Comment by DJaeger** [comment]
I'm not sure, what you mean.
Could you please clearify and/or upload a screenshot of what you mean?

**Comment by DJaeger** [comment]
Could you please describe what you mean else I will close this issue, thanks

**Comment by guidovanharten** [comment]
I see a chapter OAuth 2 which contains 'Redirect URIs'. There I only see one line to enter a URL. In your manual you wrote two lines (one for user storage and one for global storage):

For adding global storages:
https://mynextcloud.example.com/settings/admin/externalstorages
and for user storages:
https://mynextcloud.example.com/settings/admin/externalstorages

**Comment by DJaeger** [comment]
After adding one uri you can add another one and so on
