### ISSUE TITLE
Breaks NextCloud on install

### ISSUE THREAD

**Issue by lanceharvie** [DJaeger/files_external_dropbox#17]

**Comment by petestanley** [comment]
Seeing the same issue. WebUI won't load any pages after installation - Say's "Contact admin". Please let me know if I can pull some logs to help.

**Comment by petestanley** [comment]
Never mind, turns out I just needed to enable Nextcloud's external storage support first before installing/enabling this integration.

**Comment by lanceharvie** [comment]
Excellent! - there should be some error message that should pop up to state this to avoid others having the same issues

**Comment by petestanley** [comment]
To be fair this is an message displayed from NextCloud that say's there will be instability if enabled after installation.

**Comment by LgWagon** [comment]
External storage support should be enabled before installing dropbox sync app. Just in case you didn't enable it, and Nextcloud is broken (i.e.: contact admin), the solution is:
- Navigate to the Nextcloud installation folder
- Disable both the external file storage sync app and the dropbox sync app:
 sudo -u www-data php occ app:disable files_external  
 sudo -u www-data php occ app:disable files_external_dropbox
- Restart server:
   sudo reboot
Now it should work.

**Comment by DJaeger** [comment]
This error was fixed in v1.4.1, that is now uploaded to app store.
Please update and report back if it resoves your error on installing.

**Comment by LgWagon** [comment]
> This error was fixed in v1.4.1, that is now uploaded to app store.
> Please update and report back if it resoves your error on installing.

In version 1.4.1 clicking on "grant access" button did not open the Authorization page in my NC 18. So it is unusable..

**Comment by DJaeger** [comment]
Thats another issue: #9
