### ISSUE TITLE
Nextcloud 19??

### ISSUE THREAD

**Issue by nsturtz** [DJaeger/files_external_dropbox#23]
Will you plan to add nextcloud 19?

**Comment by colemamd** [comment]
According to [this](https://github.com/DJaeger/files_external_dropbox/pull/21#issue-472127211) the next version will support Nextcloud 19. https://github.com/DJaeger/files_external_dropbox/pull/21#issue-472127211

**Comment by DJaeger** [comment]
An Update, thats support Nextcloud 19, is now released with version 1.4.3 on Github and in AppStore.
