### ISSUE TITLE
Availability for NC version 20.x

### ISSUE THREAD

**Issue by Upperholme** [DJaeger/files_external_dropbox#28]
Hi. Thanks for making this. Hoping that you are planning to make this app available for version 20.x release of Nextcloud. Or confirmation that the current release is compatible with NC 20.

**Comment by Cormoran96** [comment]
Yes it is. I update my nextcloud to 20.0.2 and files_external_dropbox works perfectly

**Comment by Upperholme** [comment]
Thanks. Good to know.
