### ISSUE TITLE
Nextcloud 17.0.0 Integration

### ISSUE THREAD

**Issue by rpacewicz** [DJaeger/files_external_dropbox#6]
Hi.
Is there updated version of "External Storage backend for Dropbox" compatible with NextCloud 17.0.0?

**Comment by DJaeger** [comment]
It will, but the version for NC16 is only one week old.
You could test the current Version with NC17 by manually extending the compatible version in ```appinfo/info.xml```

**Comment by mrsnax** [comment]
please make support for 17.0.0

**Comment by DJaeger** [comment]
Could you please retry with the replaced Release-File?
The old file missed dependencies

**Comment by rpacewicz** [comment]
Hi,
I didn't know that **"External storage support"** app has to be installed before **"External Storage backend for Dropbox**". I installed **"External Storage backend for Dropbox**" without **"External storage support"** and that operation made my NextCloud not working at all. I had to manually delete **"External Storage backend for Dropbox**" folder via FTP to work it back again (/public_html/......./apps/files_external_dropbox).

**Comment by rpacewicz** [comment]
Now when I have **"External..."**  looks like it is working now. But I can't get access to Dropbox account.
![screenshot 2019-11-09](https://user-images.githubusercontent.com/11752480/68526213-c08f5880-02d9-11ea-9f9b-8bf2089e9bfe.jpg)

**Comment by rpacewicz** [comment]
I went through this manual: [https://docs.nextcloud.com/server/12.0/admin_manual/configuration_files/external_storage/dropbox.html](url)

But had to do additional step.


I put "App key" "App secret" as "Client ID" and "Client Secret"
![screenshot 2019-11-09 (2)](https://user-images.githubusercontent.com/11752480/68526528-4fea3b00-02dd-11ea-9207-4163b517f286.jpg)

And then Dropbox let me in. But prompted that I have "Invalid redirect_uri: " So I copied addres that was required into "OAuth 2 / Redirect URIs" . It works now.

![screenshot 2019-11-09 (3)](https://user-images.githubusercontent.com/11752480/68526771-8c1e9b00-02df-11ea-800b-c1b7445adf92.jpg)
![screenshot 2019-11-09 (4)](https://user-images.githubusercontent.com/11752480/68526772-904ab880-02df-11ea-9976-c54075597af2.jpg)

**Comment by wagnergerald** [comment]
Just sucessfully tried the (untested) app with version 1.2.0 and my nextcloud installation 17.0.1.

Browsing on the web is working quite slowly on my raspberry pi 3.

**Comment by DJaeger** [comment]
The process for OAuth ist completely documented here:
https://github.com/DJaeger/files_external_dropbox/blob/master/README.md#configuring-oauth2
Should also be included in the AppStore description.

Thanks for testing with NC17

**Comment by darkmattercoder** [comment]
I cannot get it to work with my nc17:

`./occ app:enable files_external_dropbox
App "External Storage backend for Dropbox" cannot be installed because it is not compatible with this version of the server`

**Comment by wagnergerald** [comment]
IIRC I enabled it with the admin apps-UI, there is a red "danger button" that allows you to enable apps for _untested_ NC versions

**Comment by ThorstenUm** [comment]
Hi,
is it known when we can expect a working update of the Dropbox connection to Nextcloud 17?

**Comment by conradp24** [comment]
Hi, I'm on Nextcloud 17, and following the OAuth documentation I've set up an external Dropbox. Thank you for your work on this, I desperately needed to collaborate with a Dropbox heavy user. The only issue I've got is that I cannot access the folders they've shared from their Dropbox to mine. Is there a way of doing this??

**Comment by wagnergerald** [comment]
The files_external_dropbox implementation is based on https://github.com/Hemant-Mann/flysystem-dropbox which is based on the dropbox v2 API. 
I just tested the V2 API and the list_folder endpoint at least returns the content of a shared folder e.g.:
`    "entries": [{ /* Shared folder*/
            ".tag": "folder",
            "name": "Sync",
            "path_lower": "/sync",
            "path_display": "/Sync",
            "id": "id:<id>",
            "shared_folder_id": "<id>",
            "sharing_info": {
                "read_only": false,
                "shared_folder_id": "<id>",
                "traverse_only": false,
                "no_access": false
            }
        }, { /* Non shared folder*/
            ".tag": "folder",
            "name": "NonShared",
            "path_lower": "/nonshared",
            "path_display": "/NonShared",
            "id": "id:<id>"
        },
`
So without looking into any could it seems not impossible that it could work ...

Do you see the folders and what does your log output look like?

**Comment by eitzenbe** [comment]
When trying to dropbox i get error 400

Nextcloud: 18.0.3

![Screenshot_20200401_020217](https://user-images.githubusercontent.com/5560776/78086002-e74f4800-73bc-11ea-8c35-97b33e2adb3b.png)

password is definitely correct

![Screenshot_20200401_020409](https://user-images.githubusercontent.com/5560776/78086071-241b3f00-73bd-11ea-863d-64d5144126bf.png)

**Comment by tmerten** [comment]
@DJaeger : Just FFY

I bumped the version to 18 and after applying a similar hack as @rpacewicz the authentication worked like a charm with an NC 18 instance. All I had to do was to use
`https://mynextcloud.example.com/settings/admin/externalstorages` as redirect URI (no second URI was needed.)

However, afterwards I get the attached stack trace.

[dropbox_nc_trace.txt](https://github.com/DJaeger/files_external_dropbox/files/4428369/dropbox_nc_trace.txt)

**Comment by DJaeger** [comment]
New version is out
The process for OAuth is now includes in the Appstore Description
files_external is automatically activated
max-version is now 17

I will test version 18 and will publish a new version

**Comment by andreascschmidt** [comment]
Hi, just installed NC18 and run into that one .. 
my granting with the URL went fine once I retun from dropbox it shows me ... 
![image](https://user-images.githubusercontent.com/11931192/82121130-abace980-9782-11ea-9c21-f26406be0105.png)
what am I missing? 
Thanks

**Comment by stefanochiappini** [comment]
Hi, I'm in the same situation as andreascschmidt: NC18 and same error.
Any hint ?
Thanks

**Comment by DJaeger** [comment]
Please check issues #9 and #13
