### ISSUE TITLE
Breaks the entire Nextcloud instalation

### ISSUE THREAD

**Issue by tiotrom** [DJaeger/files_external_dropbox#7]
I am using NextCloud 16.0.5 Stable. I installed the app via the apps dashboard. Once installed the entire nextcloud installation stops working. 500 server error. The only way to bring back my nextcloud instance is to manually delete the dropbox app files via sftp.

**Comment by DJaeger** [comment]
Have you recognized issue #5 and the proposed workaround?

**Comment by tiotrom** [comment]
I have to mention that for one I installed Nextcloud with their web installer, and second I don't have root access to the server. So that solution I don't think works for me.

**Comment by DJaeger** [comment]
The wrong file is now replaced at the Github-Release and also within the AppStore.
Remove the app and replace/reinstall should solve this issue.

**Comment by d-tamm** [comment]
This plugin still broke my installation with an internal server error. On Nextcloud 22.2.8. Recovered by disabling the plugin via occ command.
